#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a custom HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to redirect /redirect_me to another page
sudo sed -i '/server_name _;/a \\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart nginx to apply changes
sudo service nginx restart

# Check if nginx is running and listening on port 80
if sudo netstat -tuln | grep -q ':80.*LISTEN'; then
    echo "Nginx is running and listening on port 80."
else
    echo "Failed to start Nginx or bind to port 80."
    exit 1
fi
