#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart nginx to apply changes
sudo service nginx restart

# Check if nginx is running and listening on port 80
if sudo netstat -tuln | grep -q ':80.*LISTEN'; then
    echo "Nginx is running and listening on port 80."
else
    echo "Failed to start Nginx or bind to port 80."
    exit 1
fi
